; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
default_envs= release

[common]
platform = ststm32
board = genericSTM32F446RE
framework = stm32cube
upload_protocol = stlink
debug_tool = stlink

;undefines default build flags
build_unflags = 
    -DUSE_HAL_DRIVER        ;don't use HAL librarys

;defines new needed build flags
build_flags = 
    ;-DSTM32F334x8          ;already set by default
    -DUSE_FULL_LL_DRIVER    ;use ll librarys
    ;-DUSE_FULL_ASSERT      ;use stm32 assert
    -std=c99                ;use c99 standard (newer standards also possible, see gcc compiler options)
    ; -v                     ;enables verbose output

[env:release]
build_type=release
extends=common
build_flags = 
    ${common.build_flags}
    -O2

[env:debug]
extends=common 
build_type=debug 
build_flags = 
    ${common.build_flags}
    -O0
    -g3
